### ISSUE TITLE
Error running `node ./node_modules/vscode/bin/install`

### ISSUE THREAD

**Issue by aioutecism** [Microsoft/vscode-extension-vscode#10]
Hi, I just updated my extension's dependencies to `"vscode": "^0.11.0"` and appended `"post install": "node ./node_modules/vscode/bin/install"` to `scripts` in `package.json`.
I'm getting error running `npm install` which seems to be something wrong in `node ./node_modules/vscode/bin/install`.

```
➜  vscode-vim feature/update-dependencies ✓ npm i
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

> amvim@0.0.12 postinstall /Users/aioutecism/Gits/vscode-vim
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^0.10.8
Error installing vscode.d.ts: TypeError: Invalid Version: release/0.10.1-extensionbuilders

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/aioutecism/.nvm/versions/node/v5.5.0/bin/node" "/Users/aioutecism/.nvm/versions/node/v5.5.0/bin/npm" "i"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! amvim@0.0.12 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amvim@0.0.12 postinstall script 'node ./node_modules/vscode/bin/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the amvim package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/vscode/bin/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs amvim
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls amvim
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aioutecism/Gits/vscode-vim/npm-debug.log
```

**Comment by aioutecism** [comment]
I created a branch here: https://github.com/aioutecism/amVim-for-VSCode/tree/feature/update-dependencies

BTW, the newest `yo code` got the same error.

**Comment by bpasero** [comment]
@aioutecism great catch, fixed with 0.11.1. But I also found out that a bad tag name in the vscode repo caused this and removed that so it should even work without updating the vscode dependency.

**Comment by aioutecism** [comment]
Works great now! thx!

**Comment by tommck** [comment]
I just received this same error with a brand new "yo code" setup

**Comment by bpasero** [comment]
@tommck I cannot reproduce, here is what I did:
* `npm install -g generator-code`
* `yo code`
* pick the typescript variant and wait until finished

What output do you get?

**Comment by tommck** [comment]
I think the problem might be because of an http proxy we have in place that won't let something download.  I'll have to test again in a bit
