### ISSUE TITLE
Languageserver CompletionItem Textedits are executed the wrong way round

### ISSUE THREAD

**Issue by peni4142** [Microsoft/vscode-extension-vscode#109]
Hi I recognized that first executed additionalTextEdits, after that the textEdit is executed.

As example we have a textEdit:"mode" and additionalTextEdits:["Hello"]. The cursor is on the end of the line, so we can't add more range to additionalTextEdits.

If we have written mo of mode it will look like that:
=> moHelmode

Step by Step;
mo => moHello => moHelmode

My versions are all up to date. This extension is based on:
https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample

**Comment by bpasero** [comment]
@dbaeumer not sure where this should go?

**Comment by dbaeumer** [comment]
@bpasero will take care of it.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/language-server-protocol/issues/471
