### ISSUE TITLE
CODE_TESTS_WORKSPACE not used?

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode-extension-vscode#11]
Looking at the code of [/bin/test](https://github.com/Microsoft/vscode-extension-vscode/blob/8bae476df40e2ac41922ae8e694785dd20698de0/bin/test).

```CODE_TESTS_WORKSPACE``` gets assigned to ```testsWorkspace``` on lIne 20.

But ```testsWorkspace``` doesn't get used after that. I think it's meant to be used on line 33 as the first arg in the array, in place of ```testsFolder```.

**Comment by bpasero** [comment]
Thanks, good catch!
