### ISSUE TITLE
What is the right way to add icons to tree-view?

### ISSUE THREAD

**Issue by TqrHsn** [Microsoft/vscode-extension-vscode#110]
Hi,

I am specifying icon for a TreeItem like this:

`public readonly iconPath = {`
            `light: path.join(__filename, '..', '..', 'resources', 'light', 'name_16x.svg'),`
            `dark: path.join(__filename, '..', '..', 'resources', 'dark', 'name_16x.svg')`
       ` }`

but when I debug the extension or package it and install the vsix. It does not show the icon. And I can see that resources directory is not copied in out directory. I also could not find it in any of the samples.

Am I missing something? Please direct me to the docs if available.

**Comment by bpasero** [comment]
Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
