### ISSUE TITLE
Update mocha dependency

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-extension-vscode#112]
npm audit reports critical issue (see below) that can be addressed by updating the devDependency to the latest mocha version.
```
 Critical        Command Injection
  Package         growl
  Dependency of   mocha [dev]
  Path            mocha > growl
  More info       https://nodesecurity.io/advisories/146
```

**Comment by bpasero** [comment]
Looks good to me now, probably mocha was updated:

![image](https://user-images.githubusercontent.com/900690/40416786-74e2f64a-5e7e-11e8-80ad-be2c99d06b67.png)
