### ISSUE TITLE
Property 'createWebviewPanel' does not exist on type 'typeof window'.

### ISSUE THREAD

**Issue by Borvik** [Microsoft/vscode-extension-vscode#113]
TypeScript is reporting this error.  While debugging, if I ignore the error it does appear to work.  So it looks like the API exists, but didn't make it to the typescript definition files.

Using: 
Visual Studio Code: 1.23.1
Dev Dependency:
"vscode": "^1.1.17"

**Comment by Borvik** [comment]
Follow-up:  It looks like the Webview may be a proposed API, and that may be the cause.

However, the documentation https://code.visualstudio.com/docs/extensions/webview does not really even hint at that, and by extension seems like it should be usable.

**Comment by gregvanl** [comment]
Hi @Borvik createWebviewPanel is part of the stable API as of release 1.23 and available in the current version of vscode.d.ts. Perhaps you need to refresh your vscode npm module or review the "vscode" version in devDependencies.

**Comment by Borvik** [comment]
Yup - can't believe I missed trying the refresh.  That took care of it.
