### ISSUE TITLE
Auto-Completion in CDATA

### ISSUE THREAD

**Issue by peni4142** [Microsoft/vscode-extension-vscode#114]
I am working on a extension for a xml-based-language. I get code-completion in CDATA-Blocks, which is very uncool. As example someone wants write "item" followed by a return and "Item" is already written before, than "item" will beome Item. So I tried follwing in the language-configuration.json:
```
{
    "comments": {
        // symbols used for start and end a block comment. Remove this entry if your language does not support block comments
        "blockComment": [ "<![CDATA[", "]]>" ],

    },
    // symbols used as brackets
    "brackets": [
    ],
    // symbols that are auto closed when typing
    "autoClosingPairs": [
        {
            "open": "\"",
            "close": "\""
        },
        // testing if configuration is active
        {
            "open": "a",
            "close": "cc"
        },
        {
            "open": "'",
            "close": "'"
        }
    ],
    // symbols that that can be used to surround a selection
    "surroundingPairs": [
    ]
}
```

My user-settings:
```
"editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": true
    }
```

If the user is writing on a comment or CDATA-block the completion-server returns an empty array

But I can't prevent the completion from vscode.

**Comment by bpasero** [comment]
This is not the right place to ask this, please post at https://stackoverflow.com/questions/tagged/visual-studio-code
