### ISSUE TITLE
Remove url-parse dependency

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-extension-vscode#115]
For `vscode-languageserver-node`:

![image](https://user-images.githubusercontent.com/4033249/44224415-27f24300-a13f-11e8-8d47-abf64b729860.png)

I suggest that we remove `url-parse`, as it's not being used much anyway:

- You can check if the URL starts with `http` or `https` without the `url-parse` library: https://github.com/Microsoft/vscode-extension-vscode/blob/master/lib/shared.ts#L32-L38. Alternatively, we can use our own `vscode-uri` that doesn't have any dependencies.
- `request` can take a URL directly here: https://github.com/Microsoft/vscode-extension-vscode/blob/master/lib/shared.ts#L40

**Comment by bpasero** [comment]
Closing as invalid, you just need to use our latest version (see https://github.com/Microsoft/vscode-extension-vscode/commit/47f02ad0618869686599ddec6f4239dbce487802 where I updated that dependency).
