### ISSUE TITLE
Vendoring vscode.d.ts in an extension

### ISSUE THREAD

**Issue by tdyas** [Microsoft/vscode-extension-vscode#120]
My company has an internal extension for which we would like to avoid the dependency on downloading the `vscode.d.ts` file each time we build the extension (especially for CI). Is there a suggested way of vendoring this file?

It looks like that https://github.com/Microsoft/vscode-extension-vscode/blob/master/bin/install will always download `vscode.d.ts`. Would this script be an appropriate place to check to see if the extension already has a vendored copy of `vscode.d.ts`?

Note: Vendoring `vscode.proposed.d.ts` is already an "official" suggestion so I'd like to support this for `vscode.d.ts`. See https://github.com/Microsoft/vscode/blob/220bff273eed39013f24b6d26fc17f2a742ce10f/src/vs/vscode.proposed.d.ts#L14

**Comment by danmarshall** [comment]
Here's what I did: 
1. copied `vscode.d.ts` from `node_modules/vscode` to `src/`
1. check this in
1. removed `"postinstall": "node ./node_modules/vscode/bin/install",` from `package.json`

**Comment by tdyas** [comment]
That worked. Thanks!
