### ISSUE TITLE
Reduce dependency size

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-extension-vscode#122]
```bash
 hellocode-minimal-sample > yarn add vscode
 hellocode-minimal-sample > ls -la ./node_modules/ | wc -l
     206
 hellocode-minimal-sample > du -h -d 0 node_modules
 14M    node_modules
 hellocode-minimal-sample >
```

Can we possibly reduce the dependency size? For any extension with CI, this is downloaded for each commit they push.

One idea is to split the test script and its dependencies into another module such as `vscode-test`.

**Comment by bpasero** [comment]
@octref I would expect a much larger `node_modules` folder actually, given there is a `devDependency` to typescript which ways 35MB on my machine. Can you check if you got that too? Or did you exclude any other dependency?

@dbaeumer can you help me again, we seem to put a devDependency to typescript into the code extension generator ([here](https://github.com/Microsoft/vscode-generator-code/blob/master/generators/app/templates/ext-command-ts/package.json#L30)) which seems rather outdated (2.6.1). As far as I remember the idea was that VSCode would then use that typescript version found in the node modules folder and not the one we ship with. If so, we should probably bump that version up to 3.x, right?

**Comment by dbaeumer** [comment]
@bpasero we should definitely bump that yo 3.x. The reason is that when we publish we can build beforehand (in the npm script) which calls the local installed typescript compiler.

**Comment by dbaeumer** [comment]
We can rethink if this is something we want to do.

**Comment by bpasero** [comment]
Ok I can do this in the generator when I find time.

**Comment by octref** [comment]
@bpasero The default behavior of `npm i vscode` is to pull dependencies of `vscode`, not `devDependencies`. So your local dev-version of vscode would have `node_modules/typescript`, but someone installing `vscode` won't get it.

@bpasero I'm planning to make it simpler to get started with the generator. I can include updating TypeScript in my PR too.

![image](https://user-images.githubusercontent.com/4033249/48727274-a3eca300-ebe6-11e8-95ca-140c97505d11.png)

**Comment by bpasero** [comment]
@octref I know that but the generator produces a `devDependency` onto TypeScript as well which gets installed on the CI machines, no?

**Comment by octref** [comment]
@bpasero I get your points now — `typescript` is the large deps so removing deps from `vscode` won't help much.

However my use cases are:
1. Our samples at https://github.com/Microsoft/vscode-extension-samples, probably only 10% of them use the test scripts
2. JS based extensions, like https://github.com/Microsoft/vscode-extension-samples/tree/master/hellocode-minimal-sample
3. Some of my extensions covered by unit tests (not the .vscode-test integration tests)

All they need is a simple script to download the correct dts file, but now when they install `vscode` the `test` script accounts for 95% of the deps that come in & are not used.

But thinking back, most of the Ci have caching support now for yarn/npm, so this might not be a problem at all...

**Comment by bpasero** [comment]
> But thinking back, most of the Ci have caching support now for yarn/npm, so this might not be a problem at all...

Yeah, my thinking as well.

**Comment by octref** [comment]
OK closing this. My case is similar to https://github.com/Microsoft/vscode-extension-vscode/issues/120. I guess I can write a simple cli module like `vscode-dts`, so you can run things like:

```bash
npx vscode-dts 1.26 # Downloads 1.26 dts to /
npx vscode-dts 1.26 src/vscode.dts # Downloads 1.26 dts to /src
npx vscode-dts -p src/vscode.proposed.d.ts # Download proposed dts to /src
```
