### ISSUE TITLE
add flag / env var to enable downloading and unzipping to `.vscode-test` without running tests...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode-extension-vscode#124]
currently the `bin/test` script will download and unzip the vscode executable - creating the `.vscode-test` directory within your project - then attempt to run tests ([code](https://github.com/Microsoft/vscode-extension-vscode/blob/b4e20e2bed488f6a52dcef7c35131f08d5ba3ecf/bin/test#L146)).

it'd be helpful if there was a way to disable running tests and instead only do the steps required to get a local copy of vscode into the `.vscode-test` directory.

**Comment by busticated** [comment]
related conversation over here 👉 https://vscode-dev-community.slack.com/archives/C74CB59NE/p1541799580061400

**Comment by busticated** [comment]
somewhat related to https://github.com/Microsoft/vscode-extension-vscode/pull/111 since the steps you need in order to run tests when your extension has a hard dependency on a 3rd party extension are:

1. install `.vscode-test` bits (local copy of `code`)
2. install 3rd party extensions
3. run tests

currently, you can't execute step 2 without first executing step 1 but there's no way to execute step 1 without also executing step 3 which will fail due to you not having executed step 2. 🤗 wheee!

**Comment by busticated** [comment]
i'd be happy to make a PR if that's helpful 👍

**Comment by octref** [comment]
This is now available through https://github.com/microsoft/vscode-test.

See https://github.com/octref/vscode-test-sample for sample usage.
