### ISSUE TITLE
1.22 is still vulnerable to event-stream vulnerability

### ISSUE THREAD

**Issue by ruslan-bikkinin** [Microsoft/vscode-extension-vscode#128]
1.22 is still depend on vulnerable `gulp-untar@0.0.7`, though the fixed version is 0.0.8.

https://github.com/Microsoft/vscode-extension-vscode/blob/master/package-lock.json#L797
https://github.com/Microsoft/vscode-extension-vscode/blob/master/package-lock.json#L801
```
+-- vscode@1.1.22
| +-- gulp-remote-src-vscode@0.5.1
| | `-- event-stream@3.3.4
| +-- gulp-symdest@1.1.1
| | `-- event-stream@3.3.4
| +-- gulp-untar@0.0.7
```

Fix in `gulp-untar`: https://github.com/jmerrifield/gulp-untar/commit/5e6d136a99b47302feaf2b67ba70d0d2b68b2780

Commit history:
![image](https://user-images.githubusercontent.com/30265843/49296844-5c112a00-f4ca-11e8-92cb-e35b5ca64a04.png)

**Comment by bpasero** [comment]
~/development/vscode-extension-vscode> git describe --tags
1.1.23
~/development/vscode-extension-vscode> npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 893 scanned packages
