### ISSUE TITLE
Missing typings for latest vscode-languageclient

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-extension-vscode#130]
The latest vscode-languageclient (5.2.1) uses some api like `DefinitionLink` and `code.FoldingRange[]` which the latest vscode typings (1.1.26) don't expose.

**Comment by dbaeumer** [comment]
@kumarharsh these typings are in the vscode.d.ts version `^1.30`. If you already have an extension using the lsp client then you need to run `npm run postinstall` after updating the vscode engine field to `1.30`:
```
	"engines": {
		"vscode": "^1.30"
	}
```

**Comment by kumarharsh** [comment]
Thanks for the explanation @dbaeumer. I am a little confused how updating the engine would update the vscode version, when the latest version published on npm is still 1.1.26 (https://www.npmjs.com/package/vscode)

**Comment by dbaeumer** [comment]
You need to update the engine and run `npm run postinstall`. This script fetches the typings according to the engine field from GitHub.
