### ISSUE TITLE
Missing error messages for bad setup

### ISSUE THREAD

**Issue by peni4142** [Microsoft/vscode-extension-vscode#135]
#### set CODE_TESTS_PATH=D:\\not\\the\\path\\to\\extension &  node .\node_modules\vscode\bin\test

Pointing to the wrong directories (extension and tests) will just return Error: Exited with code 1. Took me some hours to make that problem out in an Azure DevOps environment.

An maybe use the path module from node.js to nomralize that. So there is not that much extra work to test in a different environment.

**Comment by bpasero** [comment]
This should work a lot better with my fixes in https://github.com/Microsoft/vscode/commit/42d0a188fce105d30c7a4388c6415c2e3183f375#diff-c61682f360a18cf690ac59fe3f625db7
