### ISSUE TITLE
vscode-install failed for vscode module

### ISSUE THREAD

**Issue by wiener0zyj** [Microsoft/vscode-extension-vscode#138]
- VSCode Version: 1.31.0(insider)
- OS Version: Win10

Steps to Reproduce:

1. run npm install for the configuration "postinstall": "vscode-install && node ./node_modules/vscode/bin/install"

2. get the error: 
Error installing vscode.d.ts: Error: read ECONNRESET
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lispvsext@0.0.1 postinstall: `vscode-install && node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lispvsext@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhangyunjin\AppData\Roaming\npm-cache\_logs\2019-01-21T02_16_08_792Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lispvsext@0.0.1 postinstall: `cd extension && npm install && cd ..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lispvsext@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhangyunjin\AppData\Roaming\npm-cache\_logs\2019-01-21T02_16_08_883Z-debug.log

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This sounds like an issue with your internet connection ("ECONNRESET") and not VSCode. I suggest you look into that.

**Comment by wiener0zyj** [comment]
Maybe, I am in china, I just tried to create an ECS machine in american. and run "npm install". It success. the output is as following:
```
Detected VS Code engine version: ^1.23.0
Found minimal version that qualifies engine range: 1.23.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/vscode.d.ts
vscode.d.ts successfully installed!
```
And my local machine in china always get this failure:
```
Detected VS Code engine version: ^1.23.0
Error installing vscode.d.ts: Error: read ECONNRESET
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lispvsext@0.0.1 postinstall: `vscode-install && node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lispvsext@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

could you confirm this is a network error, and do I have any way to solve this problem?

**Comment by wiener0zyj** [comment]
@bpasero please

**Comment by wiener0zyj** [comment]
@bpasero we have finally resolved the problem. the situation is:
IN CHINA
1. node v8.12.0 could not work, because "getURLMatchingEngine" failed with url "https://vscode-update.azurewebsites.net/api/releases/stable"
2. node v10.15.0 could work

IN AMERICAN
both node v8.12.0 and node v10.15.0 could work

**Comment by xianghongai** [comment]
```
> vscode-opened-editors@0.0.1 postinstall C:\Users\ghc-xianghongai\me\add-ons\vscode-opened-editors
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: *
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/master/src/vs/vscode.d.ts
Error installing vscode.d.ts: Error: read ECONNRESET
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-opened-editors@0.0.1 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-opened-editors@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\nodejs\node_cache\_logs\2019-12-26T03_11_22_106Z-debug.log
```

**Comment by tsssp** [comment]
windows 10 64bit;
node 10.16.1;
npm 6.9.0

> 
> > node-debug2@1.42.1 postinstall C:\TP\files\work\vscode-node-debug2-1.42.1
> > node ./node_modules/vscode/bin/install
> 
> Detected VS Code engine version: ^1.31.0
> Found minimal version that qualifies engine range: 1.31.0
> Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/7c66f58312b48ed8ca4e387ebd9ffe9605332caa/src/vs/vscode.d.ts
> Error installing vscode.d.ts: Error: read ECONNRESET
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-debug2@1.42.1 postinstall: `node ./node_modules/vscode/bin/install`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-debug2@1.42.1 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2020-04-02T23_34_46_039Z-debug.log
>

**Comment by octref** [comment]
That error would indicate that you failed to connect to GitHub. Can you check if you are able to connect to https://raw.githubusercontent.com/Microsoft/vscode/7c66f58312b48ed8ca4e387ebd9ffe9605332caa/src/vs/vscode.d.ts?
