### ISSUE TITLE
Can this module point to microsoft/vscode?

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-extension-vscode#149]
Ref: https://github.com/Microsoft/vscode/issues/70175

When I'm publishing `@types/vscode`, the linter would fail if I use microsoft/vscode as the project: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode/index.d.ts#L2

Because `@types/vscode` has to point to the same project that `vscode` points to.

**Comment by bpasero** [comment]
@octref sorry I cannot follow, what is this about?

**Comment by octref** [comment]
- I'm starting to publish `@types/vscode` as the way to get `vscode.d.ts`
- The workflow becomes `yarn add @types/vscode` to get `vscode.d.ts` to`node_modules/@types/vscode/index.d.ts`
- To publish `vscode.d.ts` to DefinitelyTyped, https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode/index.d.ts#L2, `@types/vscode` has to point to the same "project" as the one referred by `vscode` NPM module.
- So [this line](https://github.com/Microsoft/vscode-extension-vscode/blob/master/package.json#L41) and [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode/index.d.ts#L2) must point to the same project.
- In DefinitelyTyped, I would want to use `Project: https://github.com/microsoft/vscode`. But to make the DT linter pass, `vscode` module must update its project URL.

**Comment by bpasero** [comment]
@octref oh I see, if you make a PR that I can review I can maybe argue better, but I think that should not be a problematic change.
