### ISSUE TITLE
Unable to use local URIs with vscode-resource

### ISSUE THREAD

**Issue by Octillerysnacker** [Microsoft/vscode-extension-vscode#158]
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

I have a simple extension project structured like so:
![image](https://user-images.githubusercontent.com/7697688/56459711-40190280-635d-11e9-8101-cfc55906ec25.png)

I am trying to create a Webview which loads the html in `index.html`. The file looks like this:
![image](https://user-images.githubusercontent.com/7697688/56459747-d77e5580-635d-11e9-8f62-dde815e34d9c.png)

`script.js` is simply a `console.log()` line to indicate success

`extension.ts` simply has the code to create the webview.

With this configuration, the webview works normally, and I get a `console.log()` output in the webview developer tools.

I want to use a relative URI for linking the script in `index.html` however. But when I change `src` from `vscode-resource:C:\buggedextension\home\script.js` to simply `vscode-resource:script.js`, I get `Failed to load resource: net::ERR_ACCESS_DENIED` in the webview console. For some reason, if I use a similar method to link stylesheets, there are no problems. I'm not sure why scripts don't work out the same way.

EDIT: [Here is the repo containing the project if you want](https://github.com/Octillerysnacker/bugged-extension-vscode)

**Comment by bpasero** [comment]
In the future, please post questions over at StackOverflow where we have a large community of VSCode users: https://stackoverflow.com/questions/tagged/visual-studio-code. Thanks!
