### ISSUE TITLE
Local VSCode No Longer Installed as `stable`...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode-extension-vscode#159]
hi there :wave:

it seems a recent change has caused the local `vscode` dependency to no longer be installed within a `stable` directory.

after running `npm i`, the `vscode` dependency used to download and unpack a local copy of the VSCode app here:

```
.vscode-test/stable/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
```

now it places it in a versioned directory like:

```
.vscode-test/vscode-1.33.1/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
```

_note that instead of placing it within a `stable` directory, it now places it within a directory named `vscode-1.33.1` (in this instance)_

as a result, scripts i've written to manually install my `extensionDependencies` (per https://github.com/Microsoft/vscode-extension-vscode/issues/74) are breaking b/c they can’t find the `code` binary.

looking at the [history for the `install` bin](https://github.com/microsoft/vscode-extension-vscode/commits/master/bin/install), i see that it hasn't changed in a long while so i'm guessing the change is due to a difference in the VSCode app bundle / download service but 🤷‍♂ 

fwiw, i'm running:
`vscode@v1.1.34` (the npm dependency from here)
`macOS@10.13.6`

**Comment by busticated** [comment]
fwiw, it looks like the most-recent install that came down into the `stable` directory was `v1.30.2`

from my ubuntu box i ran:

```
.vscode-test/stable/VSCode-linux-x64/bin/code --version
```

which returned:

```
1.30.2
61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
x64
```

after running `npm i` and then `ls ./packages/particle-vscode-core/.vscode-test/`, i see:

```
stable
vscode-1.33.1
```

but obviously `stable` is just a left-over from before the change - if i remove it, it's not re-installed

**Comment by octref** [comment]
> after running npm i, the vscode dependency used to download and unpack a local copy of the VSCode app here:

Nope, that's only downloaded after running the integration test script.

> scripts i've written to manually install my extensionDependencies (per #74) are breaking b/c they can’t find the code binary

Well, I don't think we ever made any promise as to which directory the binary will be downloaded to.

You can use [vscode-test](https://github.com/Microsoft/vscode-test)'s API directly to get the executable path.

So your current choices are:

- Lock to the old version of `vscode` for now.
- Make your script depend on `vscode-test` directly. (Without #157 you still need the `vscode` dependency, though). This is a work in progress that hopefully will make it easier to install vscode.d.ts, do integration test, etc for extensions. I suggest adopting this in a month or two.

**Comment by busticated** [comment]
thanks @octref 

> Nope, that's only downloaded after running the integration test script

ah, i see that now thanks. looking at the current logic, it seems like over time the `.vscode-test/` directory will steadily accumulate copies of the VSCode app (e.g. `vscode-1.33.1`, `vscode-1.33.2`, etc) - am i missing something? are those ever cleaned up?

> You can use vscode-test's API directly to get the executable path.

sounds good :+1: are there any plans to automatically resolve `extensionDependencies` at test-time (or otherwise) or is the official recommendation (per https://github.com/microsoft/vscode-extension-vscode/issues/74) still for extension authors to manage that themselves?

**Comment by octref** [comment]
> automatically resolve extensionDependencies at test-time

Not really, but you can easily do that with `vscode-test` API:

```ts
  /**
   * Manually download VS Code 1.30.0 release for testing.
   */
  const vscodeExecutablePath = await downloadAndUnzipVSCode()

  // Write your own logic for downloading the VSIX and installing it
  cp.spawnSync(vscodeExecutablePath, ['--install-extensions', VSIX_PATH]);

  await runTests({
    vscodeExecutablePath,
    extensionPath,
    testRunnerPath,
    testWorkspace
  })
```

**Comment by busticated** [comment]
> Not really, but you can easily do that with vscode-test API

:+1: that's what i do today but with the addition of calling `downloadAndUnzipVSCode()` myself so i can know the exec path.

> No, but .vscode-test should be put to gitignore. Having version in the dir name avoids version mismatch. See #96.

yep, pretty sure the default recommendation (and yeoman generator output) ignores `.vscode-test/` as i am currently. 

i don't yet see the benefit of having multiple versions installed within `.vscode-test/`. naively, i would think by default you'd want to look at the current extension's `engines` entry - e.g.

```json
"engines": {
    "vscode": "^1.27.0"
}
```

and simply install the latest VSCode that meets that spec into `.vscode-test/stable` but obviously i'm not as familiar with all the details as you are. 

as it is now, i don't _think_ `engines` is even being considered in this case so a version mismatch is still possible if for example your `engines` was something like `1.27.x`, no? 

i suppose it would be nice to have the option of running your tests against multiple VSCode versions but i don't see that being helpful as a default.

**Comment by octref** [comment]
> engines is even being considered in this case so a version mismatch is still possible if for example your engines was something like 1.27.x,

`engines` only matter for launching the extension in VS Code now.

> i suppose it would be nice to have the option of running your tests against multiple VSCode versions but i don't see that being helpful as a default 🤷‍♂

The default behavior is always to use latest released version with the following code:

```ts
  /**
   * Basic usage
   */
  await runTests({
    extensionPath,
    testRunnerPath,
    testWorkspace
  })
```
