### ISSUE TITLE
diff security vulnerability

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-extension-vscode#161]
`mocha@4.*` contains `WS-2018-0590` security vulnerability that was found in [diff](https://www.npmjs.com/package/diff) subdependency. In `diff` version >= 3.5.0 this vulnerability was fixed. Due to this our extensions [vscode-react-native](https://github.com/microsoft/vscode-react-native) and [vscode-cordova](https://github.com/microsoft/vscode-cordova) are vulnerable. So I recommend to bump mocha version to the most recent ones.

**Comment by SounD120** [comment]
@octref , @bpasero , do you have a chance to look at this?

**Comment by octref** [comment]
Let's track in https://github.com/microsoft/vscode/issues/75732.

**Comment by octref** [comment]
You can upgrade to `vscode@1.1.35` now.
