### ISSUE TITLE
[JS] eslint complains: "Unable to resolve path to module 'vscode'"

### ISSUE THREAD

**Issue by Domiii** [microsoft/vscode-extension-vscode#164]
Hi!

I can debug my vscode extensions just fine; however my [vscode-eslint](https://github.com/microsoft/vscode-eslint) complains that `vscode` cannot be resolved when trying to `import`, e.g:

```js
import {
  window
} from 'vscode';
```

results in:

> Unable to resolve path to module 'vscode'

(NOTE: I'm using webpack)

## My setup

It's a recent setup; my `package.json` includes (amongst others):

```
"engines": {
	"vscode": "^1.41.0"
},

...
"devDependencies": {
...
	"@types/vscode": "^1.41.0",
	"vscode-test": "^1.2.2",
...
}
```

(and yes: I cleared everything and `npm install`'ed several times)

## Problem: JavaScript?

Maybe it is because I am using JS to develop my extension? The official vscode extension samples as well as other extensions I checked out all use TS, and they work fine.

And in JS:

```js
import {
  window
} from '@types/vscode/index.d.ts';
```

works fine as well.

**Comment by bpasero** [comment]
I cannot reproduce, I suggest you do this:
* npm install generator-code
* yo code
* pick the JS extension
* set "yes" to enable ESLint

For me it seems to work fine.
