### ISSUE TITLE
vscode.raw.d.ts is missing

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode-extension-vscode#17]
I updated to `vscode@0.11.2` and it seems like the most important file (`vscode.raw.d.ts`) is missing :).

<img width="376" alt="screen shot 2016-02-29 at 20 07 53" src="https://cloud.githubusercontent.com/assets/1913805/13405752/4b0582dc-df20-11e5-93b5-8379f6128e73.png">
<img width="265" alt="screen shot 2016-02-29 at 20 08 00" src="https://cloud.githubusercontent.com/assets/1913805/13405751/4b0435f8-df20-11e5-918b-4e7170b6502c.png">

**Comment by bpasero** [comment]
@SamVerschueren that file is only needed when you create a JS only extension and is ignored in TS extensions. Do you see any issues with compiling your extension with 0.11.2?

**Comment by SamVerschueren** [comment]
It shows that the `vscode` plugin could not be found.

<img width="624" alt="screen shot 2016-02-29 at 20 18 00" src="https://cloud.githubusercontent.com/assets/1913805/13406014/9a5a9024-df21-11e5-8809-6698edeadfab.png">

**Comment by SamVerschueren** [comment]
My bad, it was something with `npm` I guess.

**Comment by SamVerschueren** [comment]
Damn, I called to early. Can't find the reason why it is going wrong. In what file are the `vscode` type definitions defined?

**Comment by bpasero** [comment]
@SamVerschueren I am not seeing that. Some ideas:
* does it happen with our new insider release only and not stable?
* does it happen with a 0.10.x release of the vscode module?

**Comment by SamVerschueren** [comment]
It happens when I install a `vscode` plugin >= 0.11.x. When using `0.10.7`, nothing is wrong. Does it has something to do with using the Code editor `0.10.7` and installing `vscode@0.11.2`?

**Comment by bpasero** [comment]
@SamVerschueren can you give me steps to reproduce please.

**Comment by SamVerschueren** [comment]
@bpasero No problem. It occurred when I wanted to bump the version in `editorconfig-vscode`. So I'll use that as reference.

```
$ git clone git@github.com:editorconfig/editorconfig-vscode.git
```

Open the project and update the `vscode` version to `^0.11.2` in the `package.json` file.

```
$ npm install
```

Open the project with VS Code and in my case, it can't find the module `vscode`.

**Comment by bpasero** [comment]
@SamVerschueren please follow http://code.visualstudio.com/Updates#_extension-authoring

In order for consuming code@0.11.x you need to add the postinstall script:

```json
"scripts": {
  "postinstall": "node ./node_modules/vscode/bin/install"
}
```

**Comment by SamVerschueren** [comment]
Alright, that explains. Maybe I'm missing something, but why not adding that `postinstall` hook to this package? It will be easily missed by developers. If adding the hook to this package isn't an option, it might be a good idea to add it to the `README` of the package. The VS Code documentation on the website is quite overwhelming, definitely for beginners.

In one of my packages, I use the `postinstall` hook as well to install extra type definitions ([angular2-polyfill/package.json#L14](https://github.com/SamVerschueren/angular2-polyfill/blob/master/package.json#L14)). It works great.

**Comment by bpasero** [comment]
@SamVerschueren postinstall scripts are not being executed when you run "npm install" from your package. The idea is that you can make a change to the engine field and just run "npm install" to fetch a newer vscode.d.ts.

I do not think this is a big deal because all new generated extensions have this postinstall hook configured by default.

**Comment by SamVerschueren** [comment]
@bpasero actually it is executed (not sure if it's new since npm@3).

![screen shot 2016-03-01 at 11 45 14](https://cloud.githubusercontent.com/assets/1913805/13424787/250631de-dfa3-11e5-82db-2d9b8bc1dc9c.png)

Which might be a cleaner solution then adding the `postinstall` hook to each individual extension. But the decision is yours to make off course :). Thanks for linking the docs btw!

**Comment by bpasero** [comment]
@SamVerschueren does not seem to work for npm@2 so we stick to this solution. It also follows our pattern of other scripts we have for extensions (e.g. prepublish).

**Comment by SamVerschueren** [comment]
@bpasero Alright, no problem :).
