### ISSUE TITLE
Update linuxExecutable to use new path(s)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-extension-vscode#19]
*Reported by @pflannery in https://github.com/Microsoft/vscode-extension-vscode/issues/*

The executable has changed from `Code` to `code` (stable) and `code-insiders` on Linux.

https://github.com/Microsoft/vscode-extension-vscode/blob/master/bin/test#L43

**Comment by bpasero** [comment]
@pflannery should be ok with vscode@0.11.7

**Comment by pflannery** [comment]
@bpasero thank you! works great now
