### ISSUE TITLE
1.0.0's typing file is empty

### ISSUE THREAD

**Issue by aioutecism** [Microsoft/vscode-extension-vscode#22]
Having `engines.vscode: "^1.0.0"` in `package.json` and run a clean `npm install` will try to download typing file from https://raw.githubusercontent.com/Microsoft/vscode/1.0.0/src/vs/vscode.d.ts .
The url is wrong. And we are getting a `vscode.d.ts` with only `Not Found` in it.

**Comment by bpasero** [comment]
@aioutecism I cannot reproduce on Mac. Can you please check what version of the vscode module your extension is depending on?

**Comment by aioutecism** [comment]
I'm currently using `^1.0.0`.
The project is [here](https://github.com/aioutecism/amVim-for-VSCode).
You can try it on master branch.

**Comment by aioutecism** [comment]
And I'm on Mac too.

**Comment by bpasero** [comment]
@aioutecism can you try again?

**Comment by aioutecism** [comment]
Problem solved! Thanks!

**Comment by bpasero** [comment]
Ok good.
