### ISSUE TITLE
Pick the latest matching version

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-extension-vscode#26]
Currently the install script picks the oldest matching version. It would make more sense to use the latest one, i.e., given the engine version "^1.0.0" one would expect that to move up to 1.2.0, 1.3.0 when these become available.

**Comment by bpasero** [comment]
Sorry, but no. Later versions might have API that previous versions do not have. If your extension declares to be compatible with ^1.0.0, we can only drag in 1.0.0.

**Comment by bpasero** [comment]
Hi Christoph btw, only saw your name now :-). Hope my comment makes sense, otherwise you can also ping me on Slack.

**Comment by chrmarti** [comment]
Hey Ben, makes perfect sense. I looked at it from the wrong side :)

**Comment by bpasero** [comment]
Allright 👍
