### ISSUE TITLE
Cannot find module 'vscode'

### ISSUE THREAD

**Issue by PatoBeltran** [Microsoft/vscode-extension-vscode#29]
I'm trying to update the `vscode` npm package to use the latest one (0.11.14), but I get the error `Cannot find module 'vscode'.` when I try the next line: 
```
import * as vscode from "vscode";
```

I see in your code that from version `0.11.9` you added `vscode.d.ts` in your `.npmignore` (also in `.gitignore`), making it not being shipped with the package. 

Before this version it was shipped and vscode was finding the module from that file.

Is there an special reason for it? How can I use the `vscode` module from my extension?

**Comment by egamma** [comment]
Please see the answer to this question: https://code.visualstudio.com/docs/extensions/debugging-extensions#_common-questions

**Comment by PatoBeltran** [comment]
Thanks you!

**Comment by gohaterahul** [comment]
I am getting the same issue, when I am trying to browserify one of my extension file. 
Could anyone please help me for this?

Thanks
