### ISSUE TITLE
Allow to run integration tests on Windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-extension-vscode#30]
_From @DanTup on August 12, 2016 13:28_

- VSCode Version: 1.4
- OS Version: Windows 10

I don't know if I'm doing this right, but I'm trying to set up my extension up on AppVeyor to run tests. It works fine on Jenkins (Linux and OS X) but fails on AppVeyor. I can repro on my Windows desktop.

I'm running `npm test` (I presume this is correct - it seems to do the expected thing on Linux/Mac) but I get this output:

```
npm test --silent
### VS Code Extension Test Run ###
Current working directory: C:\projects\dart-code
Downloading VS Code into "C:\projects\dart-code\.vscode-test" from: https://vscode-update.azurewebsites.net/1.4.0/linux-x64/stable
Running extension tests: C:\projects\dart-code\.vscode-test\VSCode-linux-x64\code C:\projects\dart-code\out\test --extensionDevelopmentPath=C:\projects\dart-code --extensionTestsPath=C:\projects\dart-code\out\test
Failed to execute tests: Error: spawn C:\projects\dart-code\.vscode-test\VSCode-linux-x64\code ENOENT
Tests exited with code: -4058
Command exited with code 1
```

It seems to be downloading a **Linux** version of code. I tracked this back to `node_modules/vscode/bin/test` which has a platform check that only supports Linux and Mac:

    var platform = (process.platform === 'darwin') ? 'darwin' : 'linux-x64';

So, two questions:

1. What's the correct way to run tests on Windows/AppVeyor (I found [this](https://github.com/Microsoft/vscode/pull/5979/files) though I'm not sure if relevant)
2. Is there any reason `npm test` can't be made to work? All the pieces are cross-platform, it would be nice if this just worked the same everywhere

_Copied from original issue: Microsoft/vscode#10474_

**Comment by bpasero** [comment]
Sorry, but we do currently not support running integration tests for extensions on Windows. See https://code.visualstudio.com/docs/extensions/testing-extensions

**Comment by DanTup** [comment]
@bpasero Thanks for clarifying. Is this something you have planned, or are there reasons not to do it? (apologies if the complications should be obvious!)

**Comment by bpasero** [comment]
If you want you can give it a shot, I do not remember the details why it fails. I think it was some electron upstream issue with Windows :-/

**Comment by DanTup** [comment]
The current failure for me is caused by the test script just not handling Windows, so it's not getting as far as running (it downloads a Linux version of Code then bombs). If you happen across any info on other causes do post them here; I might have a play if I do get some time.

**Comment by DanTup** [comment]
@bpasero Just to be clear - I'm trying to run my own extensions tests here, and not the Code test suite; not sure if that was obvious?

**Comment by bpasero** [comment]
@DanTup yeah, if you need access to the vscode API namespace, then it will currently not work. Of course any headless mocha tests would just work fine.

**Comment by DanTup** [comment]
Currently I don't use the vscode API, I can't get the tests to run at all (just the samples that call `indexOf`) because of the error in the test script?

**Comment by bpasero** [comment]
This line:

`import * as vscode from 'vscode';`

requires the full VS Code environment to be there. So yes, if you  want to run the default tests, you need the setup where it calls into our test runner.

**Comment by bpasero** [comment]
@DanTup I just gave it a try and I think it works on Windows but one of our own tests makes the run hang. 

Let me try to see if I can make this work for normal extensions 👍

**Comment by DanTup** [comment]
> So yes, if you want to run the default tests, you need the setup where it calls into our test runner.

I understand that, but it seemed to me that it was failing before it got to execution (but I didn't investigate much).

> Let me try to see if I can make this work for normal extensions :+1:

Cool; thanks! This isn't high priority for us; I currently have no tests and our build runs on Jenkins (Linux + Mac OS X) too, but obviously it'd be nice to have the full set as we do start building tests (especially with people sending PRs).

Thanks again!

**Comment by bpasero** [comment]
@joaomoreno in order for this to work I need a URL to call to download the ZIP for Windows and not the exe. Today I have a URL `https://vscode-update.azurewebsites.net/1.4.0/win32/stable` that results in the EXE being downloaded but for the tests I need the ZIP file. 

Can we add a way to get the ZIP? Maybe by me sending an `Accept` header?

**Comment by rebornix** [comment]
+1 for Windows support.

It stops me from running tests by cmd on Windows but since we can always run the test cases within Code, it's not a blocker.

**Comment by joaomoreno** [comment]
@bpasero `https://vscode-update.azurewebsites.net/1.4.0/win32-archive/stable`

**Comment by bpasero** [comment]
@joaomoreno thanks!

@DanTup pushed support with new vscode module update (0.11.16), let me know how it goes.

**Comment by DanTup** [comment]
Awesome! Do I need to wait for the next stable build to use this?

Thanks!

**Comment by bpasero** [comment]
@DanTup no, we update the vscode node module independent from releases 👍

**Comment by DanTup** [comment]
Awesome; I forced the build on AppVeyor for my test branch and it just starting working. Thank you!

**Comment by bpasero** [comment]
nice.

**Comment by rebornix** [comment]
Updated to 0.11.16 and ran tests for Vim extensions, sometimes it failed immediately with below error messages:

```
> vim@0.1.7 test C:\Users\cici\code\Vim
> node ./node_modules/vscode/bin/test

(node:6764) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:6764) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
### VS Code Extension Test Run ###
Current working directory: C:\Users\cici\code\Vim
Running extension tests: C:\Users\cici\code\Vim\.vscode-test\Code C:\Users\cici\code\Vim\out\test --extensionDevelopmentPath=C:\Users\cici\code\Vim --extensionTestsPath=C:\Users\cici\code\Vim\out\test

[[8888:5584:0816/112906:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
2964:7068:0816/112906:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1]
[[2964:7068:0816/112906:VERBOSE1:crash_service.cc(142)] window handle is 00440752
8888:5584:0816/112906:VERBOSE1:crash_service.cc(142)] window handle is 004B0260
[[2964:7068:0816/112906:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at C:\Users\cici\AppData\Local\Temp\VSCode Crashes
8888:5584:0816/112906:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\VSCode Crash Service
dumps at C:\Users\cici\AppData\Local\Temp\VSCode Crashes
[[8888:5584:0816/112906:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\cici\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
2964:7068:0816/112906:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\cici\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[[2964:7068:0816/112906:ERROR:crash_service.cc(301)] could not start dumper
8888:5584:0816/112906:ERROR:crash_service.cc(301)] could not start dumper
Error: Illegal state: missing config
Loading development extension at C:/Users/cici/code/Vim
[C:/Users/cici/code/Vim]: Overwriting extension C:/Users/cici/.vscode/extensions/vscodevim.vim-0.1.7 with C:/Users/cici/code/Vim.
Tests exited with code: 0
```

The content of crash checkpoint is

```
GBP1
20160816
2
```

**Comment by bpasero** [comment]
Thats weird. Btw we do run lots of extension tests for VS Code via Appveyor and they typically run fine. But since you run in a Electron environment you need to be aware of all the issues this brings (native crashes, out of memory, etc.).
