### ISSUE TITLE
Does not work with typescript 2, because you use Thenable

### ISSUE THREAD

**Issue by gilamran** [Microsoft/vscode-extension-vscode#32]

**Comment by bpasero** [comment]
@gilamran how did you set that up and what is the error?

**Comment by gilamran** [comment]
@bpasero just try to compile against typescript 2... the Thenable is not there...

**Comment by bpasero** [comment]
I cannot reproduce, here is what I did:
* change package.json typescript dependency to 2.0 in the extension
* delete the out folder
* use some TS 2.0 feature to make sure I am using 2.0:
```
function foo(): never {
    throw new Error();
}
```
* compile all

=> works
