### ISSUE TITLE
TS 2.x: Conflict of vscode node definitions with @types/node

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-extension-vscode#33]
_From @whitecolor on September 2, 2016 10:59_

While developing extension, some modules may require node definitions they install it as dependency in `@types/node`

But then there appear many errors of duplicate indentifier:
![image](https://cloud.githubusercontent.com/assets/736697/18201847/f139c6f8-7125-11e6-8db4-f0993526f4a0.png)

If to remove `@types/node` those modules that require it, error that can not find definitions:

![image](https://cloud.githubusercontent.com/assets/736697/18201797/961527e0-7125-11e6-9ead-d894a033d4ab.png)

It is possible to resolve the conflict?

_Copied from original issue: Microsoft/vscode#11447_

**Comment by whitecolor** [comment]
While trying to package extension:
```
d:\Code\vscode-taskmate>vsce package                                                                                                                                             
Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "npm list --production --parseable --depth=99999"                                                                       
npm ERR! extraneous: @types/node@6.0.38 d:\Code\vscode-taskmate\node_modules\@types\node    
```

**Comment by bpasero** [comment]
@whitecolor I assume you are using TypeScript 2.0 and their new way of pulling in d.ts files via npm @types?

**Comment by whitecolor** [comment]
Yes I'm on 2.1dev here.

**Comment by bpasero** [comment]
We still have to revisit extension development when using TypeScript > 1.8. For now we do not officially support it, even though it seems to work in most cases unless you use the new typings system.

**Comment by whitecolor** [comment]
Well, thanks anyway, hope you will fix it soon,  will try to workaround it for now. :ok_hand:

**Comment by bpasero** [comment]
Should be fine now when using latest vscode module in version 1.x
