### ISSUE TITLE
No tests results on appveyor

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode-extension-vscode#36]
I am trying to add appveyor testing for one of my extensions, but Appveyor doesn't seem to run the tests at all. I've copied the repo to a test repo for now:

https://github.com/HookyQR/VSCodeBeautify2

And added a deliberately failing test. The tests are reported on my PC, but they don't seem to run on Appveyor at all. Code is definitely being started, but on tests are run, and thus Appveyor reports success.

https://ci.appveyor.com/project/HookyQR/vscodebeautify2/build/1.0.2

**Comment by bpasero** [comment]
@HookyQR can you try using the same environment variables as we do in 1.5.x? https://github.com/Microsoft/vscode/blob/1.5.3/appveyor.yml

**Comment by HookyQR** [comment]
That one is designed for Typescript, which won't work because my extension is javascript - and thus has no build step. I actually started with that, then fiddled with parts of it by adding/removing bits based on what I had seen in other extension test yaml files. Nothing has worked.

Since code actually runs, is there something I need to do specifically to get it to run *with the extension* on appveyor.

**Comment by bpasero** [comment]
I meant to replace your environment variables with this:

```
environment:
  ATOM_SHELL_INTERNAL_RUN_AS_NODE: 1
```

**Comment by HookyQR** [comment]
Awesome, thanks @bpasero. (Kind of) It fails, like it should, but with no output.

When it passes though, all of the test results come out as expected.

**Comment by bpasero** [comment]
@HookyQR the output issue will likely be fixed with our 1.6 release where we update electron 👍
