### ISSUE TITLE
Update to latest typings (VSCode 1.6)

### ISSUE THREAD

**Issue by wmaurer** [Microsoft/vscode-extension-vscode#38]
The extensions API has changed for VSCode 1.6.
For example, this line I don't see in the `vscode.d.ts` in this npm package:
https://github.com/Microsoft/vscode/blob/joh/fmtprio/src/vs/vscode.d.ts#L821

Shouldn't this package be updated to reflect the latest typings?

Thx.

**Comment by bpasero** [comment]
@wmaurer See http://code.visualstudio.com/docs/extensions/debugging-extensions#_common-questions

**Comment by wmaurer** [comment]
@bpasero Ok, thanks very much, I somehow oversaw that info.
