### ISSUE TITLE
Download typings on install, or include in package

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-extension-vscode#39]
I was very confused trying to add this to an existing project, until I realized that most repos have `"postinstall": "node ./node_modules/vscode/bin/install"` to actually download vscode.d.ts.

Would it make sense to set `"postinstall": "node ./bin/install"` in 'vscode' itself so downloading typings happens when the package is installed, or including the latest typings by default, which can be overridden if an extension supports older versions?

**Comment by bpasero** [comment]
There was a reason to do it this way I think due to some NPM behaviour at that time. Anyway we cannot just change this easily without breaking existing extensions. I do not see a real bug here or problem to solve, so I will close this.
