### ISSUE TITLE
Issues when trying to update linter extension to use TypeScript 2.x

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode-extension-vscode#41]
**From the server:**

```
node_modules/vscode-jsonrpc/lib/main.d.ts(8,67): error TS2304: Cannot find name 'Thenable'.
node_modules/vscode-jsonrpc/lib/main.d.ts(46,93): error TS2304: Cannot find name 'Thenable'.
node_modules/vscode-languageserver/lib/files.d.ts(2,83): error TS2304: Cannot find name 'Thenable'.
node_modules/vscode-languageserver/lib/files.d.ts(3,158): error TS2304: Cannot find name 'Thenable'.
node_modules/vscode-languageserver/lib/files.d.ts(8,155): error TS2304: Cannot find name 'Thenable'.
node_modules/vscode-languageserver/lib/main.d.ts(144,86): error TS2304: Cannot find name 'Thenable'.
node_modules/vscode-languageserver/lib/main.d.ts(151,88): error TS2304: Cannot find name 'Thenable'.
node_modules/vscode-languageserver/lib/main.d.ts(158,92): error TS2304: Cannot find name 'Thenable'.
node_modules/vscode-languageserver/lib/main.d.ts(217,67): error TS2304: Cannot find name 'Thenable'.
src/server.ts(50,35): error TS2304: Cannot find name 'Thenable'.
```

Where should I get `Thenable` from? In the past I got it from `es6-promise`, but that causes duplicate identifier errors now.

**From the client:**

```
node_modules/vscode-languageclient/lib/codeConverter.d.ts(30,31): error TS2305: Module 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(34,49): error TS2305: Module 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(35,53): error TS2305: Module 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(69,70): error TS2305: Module 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(70,73): error TS2305: Module 'vscode' has no exported member 'DocumentLink'.
```

Is this a bug, or am I missing a dependency?

Here is a copy of the extension: [vscode-ext.zip](https://github.com/Microsoft/vscode-extension-vscode/files/560014/vscode-ext.zip) (you'll just need to run `npm install` x2)

**Comment by bpasero** [comment]
I see the issue as well. @dbaeumer can you please advise, it is easy to reproduce after downloading the zip and `npm install` in both projects. 

![image](https://cloud.githubusercontent.com/assets/900690/19857808/5bada1f8-9f7f-11e6-82a6-cd937a805eb8.png)

**Comment by glen-84** [comment]
There are also the `Module 'vscode' has no exported member 'DocumentLink'` errors.

I'd like to get my extension updated soon if possible, so any assistance would be greatly appreciated.

**Comment by bpasero** [comment]
@dbaeumer ping

**Comment by dragos** [comment]
Same problem here. No need to update to TS 2.0 actually, I saw this on a fresh checkout. Some dependencies have been silently upgraded, I see that the checkout that works uses vscode@0.11.5, the one that fails is at 0.11.8. However, I moved everything to TS 2.0 and depend on vscode@1.0.0, still fails in the same way with DocumentLink errors.

**Comment by dragos** [comment]
@evacchi provided this workaround on the ensime-vscode Gitter room:

```
"engines": {
-        "vscode": "^0.10.10"
+               "vscode": "^1.4.0"
     },
```

**Comment by egamma** [comment]
Suggest to mimik what vscode-eslint does. It is on TS 2.0. The thenable error can be worked around by adding a thenable.d.ts, pls see https://github.com/Microsoft/vscode-eslint/blob/master/eslint-server/src/thenable.d.ts.

**Comment by glen-84** [comment]
@dragos & @egamma -- Thank you! =)
