### ISSUE TITLE
Replace multiple selections

### ISSUE THREAD

**Issue by ruiquelhas** [Microsoft/vscode-extension-vscode#43]
I'm trying to replace multiple selections in a `TextEditor` by the uppercase version of each one, like the following:

```js
function replaceContents (editor) {
  return Promise.all(editor.selections.map(selection => {
    const range = new Range(selection.start, selection.end)
    const text = editor.document.getText(range) || ''

    return editor.edit(builder => {
      builder.replace(range, text.toUpperCase())
    })
  }))
}
```

The `Thenable` returned on the first `edit()` call has `true` (and the content gets correctly replaced) but the ones from the remaining calls have `false`. Am I missing something?

**Comment by ruiquelhas** [comment]
Looks like I got it wrong, for my specific case, there is no need to call `edit()` multiple times, only `replace()`.

Closing the issue. Sorry.

**Comment by RationalCoding** [comment]
@ruiquelhas The edit builder expires once that callback completes. Did you ever find a way to replace multiple selections when calling `edit()` multiple times?

We seem to be the only people on the internet who have had this problem :/

**Comment by ruiquelhas** [comment]
The way to replace multiple selections was calling `replace()` for each selection within a single `edit()` call.
