### ISSUE TITLE
How to get languageConfiguration by language id?

### ISSUE THREAD

**Issue by Dollyn** [Microsoft/vscode-extension-vscode#46]
I'm working on some extension, I want to get LanguageConfiguration(#CommentRule) by a given language id, but didn't find any api to achieve this.  Did I miss something?

**Comment by stkb** [comment]
I opened Microsoft/vscode#2871 when I was wanting this feature myself. As far as I know it's still not possible.

It may be easier just to hardcode the values into your extension yourself.

**Comment by wiggin77** [comment]
I need this as well.  I am writing an extension that enhances other language extensions and need to look up things like what autoclosing pairs are defined.

**Comment by bpasero** [comment]
Please ask this on the VSCode repo.
