### ISSUE TITLE
Request to publish a new version of vscode.d.ts

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode-extension-vscode#48]
When would you like to publish a new version, will it be published together with every vscode release, so that we can leverage vscode.d.ts change

**Comment by bpasero** [comment]
Yes, as soon as we tag VSCode on GitHub for a new release you can use it. However, you can also set the vscode engine dependency in your `package.json` to "`*`" to fetch the latest `vscode.d.ts` from master.

**Comment by Huachao** [comment]
@bpasero will a new version be published of this package for vscode Jan release?

**Comment by Huachao** [comment]
@bpasero will we have a newer version of the `vscode` package on NPM for Jan release

**Comment by bpasero** [comment]
@Huachao there were no changes, so no new release. The new API is available as soon as you set your extension to depend on 1.9!
