### ISSUE TITLE
Cannot run `bin/install` behind a proxy

### ISSUE THREAD

**Issue by bolinfest** [Microsoft/vscode-extension-vscode#49]
See https://github.com/sourcegraph/javascript-typescript-langserver/issues/69 for more context.

**Comment by bpasero** [comment]
@bolinfest does this help you? https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables

**Comment by 4mitch** [comment]
Great! Setting these env have helped me. I've also was not able to run postinstall
