### ISSUE TITLE
StatusBarItem.command may be undefined

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode-extension-vscode#50]
Currently it isn't.

**Comment by bpasero** [comment]
@KalitaAlexey can you clarify what you mean?

**Comment by KalitaAlexey** [comment]
Hello @bpasero.
There is `vscode.StatusBarItem`.
The class declares the `command` field.
Without `--strictNullChecks` it may accept `undefined`.
And if the value is `undefined` the user wouldn't be able to click on the status bar item.
With `--strictNullChecks` it may accept only `string`.

**Comment by bpasero** [comment]
@jrieken fyi

**Comment by jrieken** [comment]
true story

**Comment by jrieken** [comment]
fixed with https://github.com/Microsoft/vscode/commit/c04b0754f59e8e2048b4131d14d9191ab351f954

**Comment by KalitaAlexey** [comment]
Good. Thank you.
