### ISSUE TITLE
Please put the vscode.d.ts file in the npm package. 

### ISSUE THREAD

**Issue by fearthecowboy** [Microsoft/vscode-extension-vscode#58]
*sigh*

Not having the `vscode.d.ts` file in the actual npm package is really a pain in the ass. 

Especially if one is crafting their own build script (because perhaps I have other stuff I need to do, and already have a build script that takes care of everything else) and didn't see that is was **required** to have a `update-vscode` script in your `package.json` `scripts` section, and then run 'npm start  update-vscode' after installing to get the actual the `vscode.d.ts` file. 

Which! On top of having to run 'npm start  update-vscode', one can't even run the script directly, since it expects to have only been run via `npm`, to get the engine version from the `package.json` file.

Any particular reason that there can't be at least a current version of the `vscode.d.ts`  the package !?

Your creative-yet-fragile construction of the npm package installation makes for much time wasted in trying to solve something that should have been installed by the simple act of installing the damn package in the first place.

**Comment by pflannery** [comment]
I place mine in `postinstall` so it auto installs it upon running "npm install"  https://github.com/vscode-contrib/vscode-versionlens/blob/master/package.json#L36
But it would be cool if `vscode.d.ts` came from a package i.e. `@types/vscode` so it's automatically referenced by typescript.

Currently I'm referencing the vscode.d.ts path in my own typings file like this -> https://github.com/vscode-contrib/vscode-versionlens/blob/master/typings/vscode-typings.d.ts

**Comment by bpasero** [comment]
No plans on changing this, we dynamically have to download the vscode.d.ts based on the version your extension has. So we cannot ship the vscode.d.ts with the module. Closing.

**Comment by hediet** [comment]
> we dynamically have to download the vscode.d.ts based on the version your extension has.

Isn't this what npm's peer dependencies are used for? Instead of specifying "engines" rather have a peer-dependency to the "vscode"-package with corresponding version constraints.
