### ISSUE TITLE
Issue finding node.d.ts and index.d.ts

### ISSUE THREAD

**Issue by pr0g** [Microsoft/vscode-extension-vscode#59]
Hi there,

I am trying to update an extension I wrote for vscode a short while ago for switching between corresponding files (.h/.cpp etc. - https://github.com/pr0g/switch-corresponding) but I am running into issues trying to build/publish.

I have tried to update the extension to the latest requirements (what is needed in package.json - following this update - https://code.visualstudio.com/updates/v1_6#_extension-authoring, and the information on this page - https://code.visualstudio.com/docs/extensions/example-hello-world) but when I run `tsc -p ./` I get the error: 

typings/node.d.ts(1,1): error TS6053: File '<path/to/my/extension>/node_modules/vscode/typings/node.d.ts' not found.
typings/vscode-typings.d.ts(1,1): error TS6053: File '<path/to/my/extension>/node_modules/vscode/typings/index.d.ts' not found.

If I run `npm install` at the root of my extension I see this message:

```
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.10.2
Found minimal version that qualifies engine range: 1.10.2
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/1.10.2/src/vs/vscode.d.ts
vscode.d.ts successfully installed!
```

but if I search for `.d.ts` (`ag -g .d.ts`) I just get these results at the root:

```
typings/node.d.ts
typings/vscode-typings.d.ts
```

I've probably missed something or am doing something wrong but I'm at a loss of how to fix this. Please feel free to clone the extension and see if you can replicate the problem! 

I've published the extension a number of times before and have never had issue with this in the past, I'm not really sure what's changed.

Any information would be greatly appreciated!

Thank you for your time!

All the best!

Tom

**Comment by bpasero** [comment]
@pr0g do you have TypeScript 2.2 installed on your system?

**Comment by pr0g** [comment]
Hi @bpasero!

If I type `tsc -v` at the terminal I see I have Version 2.2.2 installed

I'm not sure if the extension somehow isn't finding it though?

Thank you for your help!


Tom

**Comment by bpasero** [comment]
@pr0g are your changes on some branch so that I can run `tsc` on it?

**Comment by pr0g** [comment]
Everything is checked in to mainline atm, if you just clone the repo in theory you should be able to see the issue I think, there's no special branch (probably should be!)

Thanks!

**Comment by bpasero** [comment]
@pr0g you can delete the top level typings folder, it is no longer needed.

Btw to get more typing, change:

```typescript
var Path = require('path');
```

to

```typescript
import * as path from 'path';
```

**Comment by pr0g** [comment]
Awesome! That has fixed it! Thank you very much indeed! 😄 

Much appreciated, have a good one!
