### ISSUE TITLE
Error running tests: TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-extension-vscode#61]
_From @kidtsunami on April 7, 2017 16:12_

- VSCode Version: v1.11.1
- OS Version: macOS v10.12.4

Steps to Reproduce:

1. Pull down MavensMate-VisualStudioCode extension from https://github.com/kidtsunami/MavensMate-VisualStudioCode/tree/command-tests
2. Run cmd `yarn`
3. Run cmd `npm test`
4. Observe:
```bash
mavensdavid:MavensMate-VisualStudioCode davidhelmer$ npm test

> mavensmate@0.6.2 test /Users/davidhelmer/Work/mavens-mate/MavensMate-VisualStudioCode
> node ./node_modules/vscode/bin/test

### VS Code Extension Test Run ###
Current working directory: /Users/davidhelmer/Work/mavens-mate/MavensMate-VisualStudioCode
Downloading VS Code into "/Users/davidhelmer/Work/mavens-mate/MavensMate-VisualStudioCode/.vscode-test" from: https://vscode-update.azurewebsites.net/1.11.1/darwin/stable
Error running tests: TypeError: Cannot read property '0' of null
npm ERR! Test failed.  See above for more details.```


_Copied from original issue: Microsoft/vscode#24236_

**Comment by chrmarti** [comment]
@kidtsunami How is this a problem with VSCode?

**Comment by chrmarti** [comment]
_From @kidtsunami on April 10, 2017 13:19_

Good question @chrmarti , I don't have any hard facts just that nothing build related changed from when tests worked to when they stopped. Why I think it's VSCode related:

1. My Travis-CI builds stopped working. Even though running tests through "Launch Tests" continued to work in VSCode, I saw the  [above error in Travis-CI](https://travis-ci.org/kidtsunami/MavensMate-VisualStudioCode/builds/207196933). [Here is a successful build previous to that build](https://travis-ci.org/kidtsunami/MavensMate-VisualStudioCode/builds/195953492). Now, I've had intermittent issues where the Linux half of the Travis-CI build inexplicably failed and I haven't taken the time to figure out why.
2. I was returning from a hiatus to change a few messages into modal dialogs for the extension and had not made any significant changes (someone had a PR for adding block comments that I merged) and was investigating why the Travis-CI was having issues and observed them locally.

I also have an issue with "Launch Tests" where it looks like it starts running before the test workspace is copied over and subsequently tests fail, I have workarounds for that and am more concerned about the above issue.

If there is a way for me to get a more detailed log beyond `npm test --verbose` let me know and I'll figure out how to eliminate VSCode as a possible cause of this.

**Comment by chrmarti** [comment]
@kidtsunami Can you get at the stacktrace of that error? Is it in extension code?

**Comment by chrmarti** [comment]
_From @kidtsunami on April 10, 2017 22:4_

@chrmarti I don't know how to get the stacktrace from running `npm test` from the command line.

Though comparing the successful build, it looks like it does not get to the point of loading the extension test. Here is the successful build log:
```bash
### VS Code Extension Test Run ###
Current working directory: /Users/travis/build/kidtsunami/MavensMate-VisualStudioCode
Downloading VS Code into "/Users/travis/build/kidtsunami/MavensMate-VisualStudioCode/.vscode-test" from: https://vscode-update.azurewebsites.net/1.8.1/darwin/stable
Running extension tests: /Users/travis/build/kidtsunami/MavensMate-VisualStudioCode/.vscode-test/Visual Studio Code.app/Contents/MacOS/Electron /Users/travis/build/kidtsunami/MavensMate-VisualStudioCode/out/test --extensionDevelopmentPath=/Users/travis/build/kidtsunami/MavensMate-VisualStudioCode --extensionTestsPath=/Users/travis/build/kidtsunami/MavensMate-VisualStudioCode/out/test
```

The key part is, the failing build, appears to fail before the `Running extension tests` line. Have there been issues in the past with the `Downloading VS Code into` step?

**Comment by bpasero** [comment]
@kidtsunami This is because of a very old vscode dependency in package.json, please update to ^1.0.0.

**Comment by iampeterbanjo** [comment]
I don't think this is just a problem with the VS code dependency. I have a failing build on Codeship and Travis which I can't fix. The build works on Mac OSX and on my local Linux machine but not on the CI servers.

I would really appreciate any help on this. This is the Git branch that I'm trying to test
https://github.com/iampeterbanjo/vscode-elixir-linter/tree/feature/16-lint-severity

**Comment by iampeterbanjo** [comment]
```
# package.json
"engines": {
    "vscode": "1",
    "node": ">=6.10.0"
  },
```

```
# .travis.yml
language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"

sudo: false

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent
```

Failing Linux build logs
![screenshot from 2017-06-22 08-33-36](https://user-images.githubusercontent.com/221853/27422409-f3ac0630-5725-11e7-9ac4-d145789b66cb.png)

Passing Mac OS X build logs
![screenshot from 2017-06-22 08-34-27](https://user-images.githubusercontent.com/221853/27422420-00044988-5726-11e7-8489-32a874a87a98.png)
