### ISSUE TITLE
API for symbolic linked folders & files

### ISSUE THREAD

**Issue by Dominik-K** [Microsoft/vscode-extension-vscode#63]
(I guess it's the right `vscode` repo.)

It would be nice to display symbolic links in the "File Icon Theme" extensions. The developers from the `vscode-icons` extension would like to implement the feature when there's an API for it. See https://github.com/vscode-icons/vscode-icons/issues/124#issuecomment-305151861

**Comment by bpasero** [comment]
@Dominik-K please report to https://github.com/Microsoft/vscode
