### ISSUE TITLE
windows 1.13.x vscode-update.azurewebsites.net archives have an incorrect zip structure

### ISSUE THREAD

**Issue by ryanluker** [Microsoft/vscode-extension-vscode#64]
The 1.13.x archives seem to be zipped incorrect as they do not have the important Code.exe file in the root. Instead code is located like this: ```Downloads\VSCode-win32-ia32-1.13.1\VSCode-win32-ia32\Code```
while previous releases it was: ```Downloads\VSCode-win32-1.11.0\Code```. This has the not so fun side effect of causing integration tests to fail:
```
### VS Code Extension Test Run ###
Current working directory: C:\dev\vscode-coverage-gutters
Downloading VS Code into "C:\dev\vscode-coverage-gutters\.vscode-test" from: https://vscode-update.azurewebsites.net/1.1
3.1/win32-archive/stable
Running extension tests: C:\dev\vscode-coverage-gutters\.vscode-test\Code C:\dev\vscode-coverage-gutters\out\test --exte
nsionDevelopmentPath=C:\dev\vscode-coverage-gutters --extensionTestsPath=C:\dev\vscode-coverage-gutters\out\test
Failed to execute tests: Error: spawn C:\dev\vscode-coverage-gutters\.vscode-test\Code ENOENT
Tests exited with code: -4058
npm ERR! code ELIFECYCLE
```
It seems directly related to the code assumption that the executable Code will always be in the root? https://github.com/Microsoft/vscode-extension-vscode/blob/master/bin/test#L24
Let me know if I am interpreting something wrong about my situation 😄 

example failing build: https://ci.appveyor.com/project/ryanluker/vscode-coverage-gutters/build/1.0.272

Thanks,

**Comment by joaomoreno** [comment]
Fixed in https://github.com/Microsoft/vscode/commit/c1562a5ebb4a072367bf528b23db3a8c91e46c7b

**Comment by bpasero** [comment]
@joaomoreno thanks 👍

**Comment by bpasero** [comment]
Unfortunately we need a new release for this to take effect. As a workaround you can set an environment variable that the test script will pick up: `set CODE_VERSION=1.12.2`

**Comment by ryanluker** [comment]
@joaomoreno @bpasero Thanks for the quick turn around guys 😄 👍
