### ISSUE TITLE
Install script doesn't honor proxy settings

### ISSUE THREAD

**Issue by bvandre** [Microsoft/vscode-extension-vscode#65]
When doing an npm install behind a proxy with `HTTP_PROXY` environmental variable set and `npm config proxy` set as well the proxy is never used.  Doing a little hacking it seems that I can get it to work by adding 

`    if (process.env.npm_config_proxy) {
        options.proxy = process.env.npm_config_proxy;
    }`

to lib/shared.js.

I wasn't sure if this would be the best solution but I can make a pull request if this looks ok.

**Comment by bpasero** [comment]
@bvandre does this help? https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables

**Comment by bvandre** [comment]
I think I was mistaken about our corporate proxy.  For some reason SSL requests use the http protocol instead of https. Setting `HTTPS_PROXY` to our internal proxy, seems to work.  

I might still argue that using the npm setting for the proxy makes a little bit more sense as it took me a while to figure out what was going on, but as long as this works I am happy.
