### ISSUE TITLE
Extension tests failing on Windows

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-extension-vscode#72]
I'm not really sure how to debug this, but my extension tests are currently failing on AppVeyor, eg:

https://ci.appveyor.com/project/DanTup/dart-code/build/0.0.591

The output is this:

```text
### VS Code Extension Test Run ###
Current working directory: C:\projects\dart-code
Downloading VS Code into "C:\projects\dart-code\.vscode-test" from: https://vscode-update.azurewebsites.net/1.13.1/win32-archive/stable
Running extension tests: C:\projects\dart-code\.vscode-test\Code C:\projects\dart-code\out\test --extensionDevelopmentPath=C:\projects\dart-code --extensionTestsPath=C:\projects\dart-code\out\test
Failed to execute tests: Error: spawn C:\projects\dart-code\.vscode-test\Code ENOENT
Tests exited with code: -4058
npm ERR! Test failed.  See above for more details.
Command exited with code 1
```

This is the same output that was given in #30 which happened when it was downloading a Linux version of code, however this time the link does say `win32`. Could there be something else wrong with the downloading/extracting of code for test runs? It happens on my local machine when I run `npm test`, not just on AppVeyor.

I've removed the `--silent` from the test run, but it didn't give any more output.

**Comment by bpasero** [comment]
Looks like https://github.com/Microsoft/vscode-extension-vscode/issues/69

**Comment by DanTup** [comment]
Yep, which was same as #64. I'm assuming the June release isn't too far away, so I'll just live with it until then; I don't have any useful tests yet anyway 😁
