### ISSUE TITLE
Failed to activate extension if there is an extensionDependencies when running test

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-extension-vscode#74]
In Travis CI, meet with below error when running `npm test --silent` since the extension has an extensionDependencies
```
Extension `vsciot-vscode.azure-iot-toolkit` failed to activate. Reason: unknown dependency `ms-vscode.azure-account`.
```
Not sure there is a way to install the required extensionDependencies or any other workaround.

**Comment by bpasero** [comment]
@formulahendry you will have to prepare the environment in a way that all required extensions are present. You can set the `process.env.CODE_EXTENSIONS_PATH` variable to point to a folder where all extensions that are required are in.

**Comment by formulahendry** [comment]
@bpasero , thanks for the info! So I need install the required extensions before running the `npm test --silent`. Is there any sample or best practice to install an extension during CI? I know there is `code --install-extension` to install ext, but you need to install vscode before that. That would be a little heavy. And I see this function will will install vscode then run tests. I am thinking is it able to install the extensionDependencies during this function?

**Comment by bpasero** [comment]
Maybe @sandy081 would know, I think you can install an extension from the command line including all dependencies.

**Comment by sandy081** [comment]
Only way I can see is to download the extension from the market place. I do not think there is a library that does it but it is not much code to write to include in your code.
