### ISSUE TITLE
SourceControlInputBox.value no longer exists

### ISSUE THREAD

**Issue by chadbr** [Microsoft/vscode-extension-vscode#76]
The SourceControlInputBox seems to have lost it's "value" implementation:

```
	/**
	 * Represents the input box in the Source Control viewlet.
	 */
	export interface SourceControlInputBox {

		/**
		 * Setter and getter for the contents of the input box.
		 */
		value: string;
	}
```

as of 1.16 - the vsts extension has lost it's ability to manipulate the commit message:

https://github.com/Microsoft/vsts-vscode/issues/314

Any ideas?

Thanks - Chad

**Comment by bpasero** [comment]
@joaomoreno can you comment?

**Comment by joaomoreno** [comment]
I'll comment on Microsoft/vsts-vscode#314
