### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode-extension-vscode#77]
`mocha` has a high priority to be updated to `v4` from `v3` due to a security risk with one of its dependencies.

**Comment by JimiC** [comment]
1. Would you like me to submit a PR for this?
2. While at it would you like to update all dependencies to the latest version?

**Comment by bpasero** [comment]
@JimiC yeah sounds good, thanks. Let's try to update them all if possible. But we need to test for each if there are semantic changes. Most dependencies seem to originate from the [`test`](https://github.com/Microsoft/vscode-extension-vscode/blob/master/bin/test) command (e.g. all gulp related dependencies).

**Comment by bpasero** [comment]
Landed.
