### ISSUE TITLE
vscode shows error message for files not part of project 

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/vscode-extension-vscode#83]
created simple test project: [link](https://github.com/CzBuCHi/vscode-wrong-error) 

**how to reproduce**
1. open test project in editor
2. start debugger session (F5) - all goo so far
3. open random typescript file in same editor with is not in `/src/**` folder and has syntax error in it.
4. vscode will correctly show problems in opened file
5. start debugger session - this popup message appears:
`Build errors have been detected during preLaunchTask 'npm: watch'. [Debug Anyway] [Show problems] [Cancel]`
but there is not errors in terminal panel `Task - watch` (because errors are in file not relevant to tsc) so i think, that error message should not be shown ...

**Comment by bpasero** [comment]
@CzBuCHi can you please report this to our VSCode issue repository here: https://github.com/Microsoft/vscode/issues
