### ISSUE TITLE
Add types for `vscode/lib/testrunner`

### ISSUE THREAD

**Issue by PranayAgarwal** [Microsoft/vscode-extension-vscode#86]
The default test runner module provided by VS Code (at `vscode/lib/testrunner`) isn't typed, so the project fails compilation with the strict-mode TypeScript compiler flag `noImplicitAny`.

Moved here from https://github.com/Microsoft/vscode/issues/38649.

**Comment by bpasero** [comment]
Care to provide a PR?

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode-extension-vscode/commit/d774e73402f048c43571f59534d852423c40b080 and published as version `1.19`.

/cc @egamma
