### ISSUE TITLE
Allow to run tests with insiders build

### ISSUE THREAD

**Issue by guw** [Microsoft/vscode-extension-vscode#88]
It's currently not possible to run VS Code Extension tests with an insiders build. 

Looking at the code it seems that setting CODE_VERSION should do the trick. However, this doesn't work because of a hard coded "stable" in the generated download url. Also, setting `CODE_DOWNLOAD_URL` directly (eg., to `https://vscode-update.azurewebsites.net/1.19.0-insider/linux-x64/insider`) won't help. The resulting executable name would be `code-insiders`, which isn't currently supported.

**Comment by guw** [comment]
@bpasero I noticed that setting `CODE_DOWNLOAD_URL` isn't a valid workaround. The executable after the download is `code-insiders`, which the `test` script doesn't support currently.

**Comment by bpasero** [comment]
Ah yeah good point.

**Comment by bpasero** [comment]
@joaomoreno would it be possible to get an endpoint in the form of: `https://vscode-update.azurewebsites.net/<platform>/insiders` that would simply return the last insiders release?

**Comment by joaomoreno** [comment]
@bpasero You mean https://vscode-update.azurewebsites.net/latest/win32/insiders ?

**Comment by bpasero** [comment]
@joaomoreno cool!

**Comment by bpasero** [comment]
@joaomoreno wait, why does that URL download 1.18.1?

**Comment by bpasero** [comment]
@joaomoreno that one downloads stable for me. How does the website get the latest insider build from https://code.visualstudio.com/insiders/ ?

**Comment by joaomoreno** [comment]
Oh https://vscode-update.azurewebsites.net/latest/win32/insider. There was an S too many.

**Comment by bpasero** [comment]
@joaomoreno thanks

@guw interested to provide this as PR? I think we should just use the insider build when the extension declares "`*`" as engine dependency. E.g.

```json
"engines": {
    "vscode": "*"
}
```

**Comment by guw** [comment]
According to [the docs](https://code.visualstudio.com/docs/extensionAPI/extension-manifest) `*` is not allowed. Should it be used anyway? Won't that cause issues at runtime?

**Comment by bpasero** [comment]
@guw yeah good point, it would probably only be useful on a branch where you want to run builds and tests explicitly against insiders. 

Alternatively we could introduce another environment variable to specify the build to be insiders.

**Comment by bpasero** [comment]
Published as 1.1.10
