### ISSUE TITLE
Breaking change (removal of vscode.d.ts) and semver

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode-extension-vscode#9]
The TravisCI Linux machine for `vscode-go` started picking up `0.10.8-pre5` recently, which doesn't include vscode.d.ts, and thus breaks the build.

https://travis-ci.org/Microsoft/vscode-go/jobs/107513941

There's a couple things that are odd here:

1. `vscode.d.ts` has been removed, but it's unclear how this is supposed to be dealt with.  It looks like there is an `npm run install` script now, but not clear what the right way to integrate that is.  Is there an example?
2. This breaking change was done under a patch version update (0.10.7 -> 0.10.8).  That means that once published without the `-pre5` it will cause any `"vscode": "^0.10.7"` dependencies to auto-move, and will be broken.
3. Strangely, it appears that NPM 1.X treats `^0.10.7` as picking `0.10.8-pre5`, bug NPM 2.X treats it as picking `0.10.7`, so I'm seeing inconsistent results on the default Mac and Linux Travis machines due to the different default NPM versions on each of these images.  Something I'll have to fix, but also suggests the problem with this versioning.

**Comment by bpasero** [comment]
@lukehoban please see https://github.com/Microsoft/vscode-docs/blob/master/release-notes/latest.md#api-consumption

It is unclear to me why npm would pick up a pre release version of a package but I have now unpublished any 0.10.8-pre releases and instead there is now 0.10.7 which is the latest version matching our old API consumption style and 0.11.0 which is for the new (breaking) style of consuming APIs.

**Comment by lukehoban** [comment]
> @lukehoban please see https://github.com/Microsoft/vscode-docs/blob/master/release-notes/latest.md#api-consumption

Great - I had missed that.

> It is unclear to me why npm would pick up a pre release version of a package but I have now unpublished any 0.10.8-pre releases and instead there is now 0.10.7 which is the latest version matching our old API consumption style 

Thanks - it looks like this has fixed the build in the `vscode-go` CI.
