### ISSUE TITLE
Prefer direct exports over "declare module"

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode-extension-vscode#90]
Currently the type definitions are written like:

```ts
declare module 'vscode' {
	export const version: string;
	...
}

interface Thenable<T> { ... }
```

But they could be written like:

```ts
export const version: string;
...

declare global {
	interface Thenable<T> { ... }
}
```

The latter is the style we recommend on DefinitelyTyped. The difference is that it makes the file into an external module that is imported based on its path, rather than an ambient declaration that can be imported from anywhere.

**Comment by bpasero** [comment]
@jrieken fyi not sure if this could be done from the vscode.d.ts we have in our repo in VSCode or we would have to massage the d.ts when downloading for this module.

**Comment by jrieken** [comment]
I believe not, esp. because we have the `vscode` module declared in two files, `vscode.d.ts` *and* `vscode.proposed.d.ts`.

**Comment by andy-ms** [comment]
Yeah, if you have two different versions of the same thing I guess you'll have to use an ambient module in at least one of them.

**Comment by bpasero** [comment]
I am closing this as I see no actionable item for the vscode module. Since the vscode.d.ts is coming from the VS Code repo, please report the issue there.
