### ISSUE TITLE
Module incompatible with Node 0.10

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-extension-vscode#91]
From @shanalikhan 

> Hello, 
> I am building the settings sync extension in my computer and it works well.
> I have recently added Travis CI and it fails 
>
> ![image](https://user-images.githubusercontent.com/8774556/35941530-5a52c424-0c74-11e8-9547-f405dd83234f.png)
> 
> https://travis-ci.org/shanalikhan/code-settings-sync/jobs/338701293

We should maybe add an engine compatibility field to this module.

**Comment by bpasero** [comment]
PR welcome.

**Comment by bpasero** [comment]
Added:

```json
"engines": {
  "node": ">=6.4.0"
}
```

Which seems to be the beginning of `const` support in node.js.
