### ISSUE TITLE
Post install script failed

### ISSUE THREAD

**Issue by SABIH-YUSSUF** [Microsoft/vscode-extension-vscode#92]
I'm using VS Code 1.20.1, When I create a new extension project using yo code, the post install script for vscode module produces the following output:

`Error installing vscode.d.ts: Missing VSCode engine declaration in package.json.`

In the package.json of the extension project:

```
"engines": {
        "vscode": "^1.17.0"
}
```

**Comment by bpasero** [comment]
@SABIH-YUSSUF can you attach the project as zip?
