### ISSUE TITLE
Add Switch for Offline Installation

### ISSUE THREAD

**Issue by amtlib-dot-dll** [Microsoft/vscode-extension-vscode#93]
When a package depends on this package, it cannot be installed without Internet access, which is bad for some build machines. [`yarn`](https://yarnpkg.com/blog/2016/11/24/offline-mirror/) has an offline installation feature; however this feature is unusable for projects with this package.

When a project releases a version with pinned and cached `vscode.d.ts` file, the release may set up a flag indicating no downloads are needed.

Thanks!

**Comment by TristanFAURE** [comment]
I'm also interested as we are downloading our dependencies using artifactory.
Most of the libraries we use provide env vars to set mirror download

**Comment by octref** [comment]
You might be interested in https://github.com/Microsoft/vscode/issues/70175.

**Comment by octref** [comment]
This is now possible through dropping `vscode` dependency and only pull types from `@types/vscode`: https://www.npmjs.com/package/@types/vscode.

We are on 1.14 now and by end of this month we should have dts up to 1.32.
