### ISSUE TITLE
API for hiding characters in a file

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [Microsoft/vscode-extension-vscode#98]
Hi,

I'm new to VSCode extension development, just had a quick read of the API reference and could not find an API I need for [my extension](https://github.com/keyvan-m-sadeghi/indented/).

## Use case

I want my extension to parse `js` files and hide the visual clutter of opening and closing braces (`{` and `}`) with a button located in the status bar (next to `TabSize`, etc.). I'd later want the extension to add the missing braces based on the indent.

## API

I need to be able to tell VSCode to hide specified (line/column start + offset) characters or lines (line number) in a file open in the editor.

**Comment by bpasero** [comment]
@keyvan-m-sadeghi please report this to our repo: https://github.com/Microsoft/vscode

**Comment by keyvan-m-sadeghi** [comment]
@bpasero hmm I'm not reporting an issue with VSCode you see, I'm proposing a feature to be added to the extensibility APIs in (this repo). If you could give me a starting point, I could cook a pull request.

**Comment by bpasero** [comment]
@keyvan-m-sadeghi yes trust me, its the right place
